/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userInterfaces;

import com.encryption.encryptionjpci.models.User;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import persist.Persist;

/**
 *
 * @author Usuario
 */
public class MainScreen extends javax.swing.JFrame {

    Persist persist = new Persist();
    DefaultTableModel dtusers = new DefaultTableModel();
    
    public MainScreen() {
        initComponents();
        
//        String[] headers = {"Nombre", "Apellidos", "Correo"};

//        dtusers.setColumnIdentifiers(headers);
    }
    
    public void loadUsers() {
              
//        tblUsers.setModel(dtusers);
        
//        for(User user : persist.users){
//            dtusers.addRow(new Object[] {user.getName(), user.getLastName(), user.getEmail()});
//        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        optRegister = new javax.swing.JMenuItem();
        optResetPassword = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );

        jMenu1.setText("Opciones");

        optRegister.setText("Registro");
        optRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optRegisterActionPerformed(evt);
            }
        });
        jMenu1.add(optRegister);

        optResetPassword.setText("Cambio de contraseña");
        optResetPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optResetPasswordActionPerformed(evt);
            }
        });
        jMenu1.add(optResetPassword);

        jMenuItem1.setText("Visualizacion de encriptado");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optRegisterActionPerformed
       RegisterScreen registerScreen = new RegisterScreen();
       EncryptDecryptScreen encryptDecrypt = new EncryptDecryptScreen();
       registerScreen.setVisible(true);
       encryptDecrypt.setVisible(true);
       encryptDecrypt.setLocationRelativeTo(null);
       registerScreen.setLocationRelativeTo(null);
    }//GEN-LAST:event_optRegisterActionPerformed

    private void optResetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optResetPasswordActionPerformed
        ResetPasswordScreen resetPassword = new ResetPasswordScreen();
        EncryptDecryptScreen encryptDecrypt = new EncryptDecryptScreen();
        resetPassword.setVisible(true);
        encryptDecrypt.setVisible(true);
        encryptDecrypt.setLocationRelativeTo(null);
        resetPassword.setLocationRelativeTo(null);
    }//GEN-LAST:event_optResetPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem optRegister;
    private javax.swing.JMenuItem optResetPassword;
    // End of variables declaration//GEN-END:variables
}
